<?php
/**
 * The file blog-home-page.phtml gets the variables below passed. The $posts contain the posts in the category, which is
 * marked as blog home page.
 */
/** @var Iterator<\App\Database\BlogPost> $posts */
$this->layout('theme::layout');
?>
<?php $this->start('maincontent') ?>
<main>
    <h1>Welcome to my blog</h1>
    <div>
        <?php foreach ($posts as $post): ?>
            <a href="/<?= $post->createdAt->format('Y/m/d') ?>/<?= $this->e($post->slug) ?>">
                <span><?= $this->e($post->title) ?></span>
                <?php if ($post->headerImageId !== null): ?>
                    <img src="<?= $post->getHeaderImage()->path ?>" alt="<?= $this->e($post->title) ?>">
                <?php endif ?>
            </a>
        <?php endforeach ?>
    </div>
</main>
<?php $this->stop() ?>
